language: python

python:
  - "3.6"
  
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls

script:
  - cd ./lab1/croptool
  - python -m unittest 
  
after_success:
  - coveralls
